---

- include: repository.yml
  tags: pgbouncer

- name: Install pgbouncer
  apt: pkg=pgbouncer state=installed
  notify:
    - restart pgbouncer
  tags: pgbouncer

- name: Install pgbouncer config
  action: template src=pgbouncer/pgbouncer.ini.j2 dest=/etc/pgbouncer/pgbouncer.ini
          mode=0644 owner={{ pgbouncer.user }} group={{ pgbouncer.group }}
  notify:
    - reload pgbouncer
  tags: pgbouncer

- template: src=pgbouncer/users.txt.j2 dest={{ pgbouncer.config.auth_file }} owner={{ pgbouncer.user }}
  notify:
    - reload pgbouncer
  tags: pgbouncer

- lineinfile: dest=/etc/default/pgbouncer regexp=^START=1$ line=START=1 state=present
  notify:
    - reload pgbouncer
  tags: pgbouncer

- lineinfile: dest=/etc/default/pgbouncer regexp=^START=0$ line=START=0 state=absent
  notify:
    - reload pgbouncer
  tags: pgbouncer

- template: src=pgbouncer/logrotate.j2 dest=/etc/logrotate.d/postgresql-common

- include: monitoring.yml
  tags: pgbouncer

- include: newrelic.yml
  when: newrelic_license_key is defined
  tags: pgbouncer

- name: Update /etc/pam.d/su file
  sudo: yes
  lineinfile: dest=/etc/pam.d/su
              regexp="^session    required   pam_limits.so"
              insertafter='^# session    required   pam_limits.so'
              line="session    required   pam_limits.so"
              state=present

- name: set postgres ulimits
  template:
    src: limits.d/postgresql.conf
    dest: /etc/security/limits.d/postgresql.conf
    mode: 644
  notify:
    - restart pgbouncer

