---
# Needed for add-apt-repository
- name: Install python-software-properties
  apt: pkg=python-software-properties state=installed
  tags:
    - apt

- name: Add repository key
  apt_key:
    keyserver: keys.gnupg.net
    id: ACCC4CF8
  tags:
    - apt

- name: Add PostgreSQL repository
  apt_repository: repo='{{ pgbouncer.repo }}' state=present
  tags:
    - apt
